name: ESP32 Arduino Libs CI

on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  group: esp-idf-libs-${{github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

jobs:
  build-libs:
    name: Build Libs for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32, esp32s2, esp32s3, esp32c3, esp32c6, esp32h2]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Build Libs for ${{ matrix.target }}
      run: bash ./build.sh -e -t ${{ matrix.target }}
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist

  inspect-artifacts:
    name: Check resulting artifacts
    needs: build-libs
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: dist
      - shell: bash
        run: ls -l dist

