name: Remote Trigger

on: repository_dispatch

jobs:
  run:
    name: Dispatch Event
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Handle Event
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        GIT_AUTHOR_EMAIL: ${{ secrets.PUSH_EMAIL }}
        GIT_COMMITTER_EMAIL: ${{ secrets.PUSH_EMAIL }}
      run: bash ./tools/repository_dispatch.sh
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist
